create table if not exists users
(
    id       bigint generated by default as identity not null,
    username varchar(32)                             not null,
    password varchar(100)                            not null,
    roles    varchar(32)                             not null,
    constraint pk_user primary key (id),
    constraint uq_user_username unique (username)
);
create table if not exists requests
(
    id      bigint generated by default as identity not null,
    status  varchar                                 not null,
    text    varchar                                 not null,
    user_id bigint                                  not null references users (id),
    created timestamp without time zone,
    constraint pk_request primary key (id)
);